version: '3.8'
services:
  minio:
      image: minio/minio
      hostname: "minio"
      env_file:
        - .env
      volumes:
        - ./minio:/minio_files
      command: 'minio server /minio_files --console-address ":9001"'
      ports:
        - 9000:9000
        - 9001:9001
        
  createbuckets:
      image: minio/mc
      depends_on:
        - minio
      env_file:
        - .env
      entrypoint: >
        /bin/sh -c "
        until( /usr/bin/mc alias set myminio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD) do echo '...Setting MinIO Credentials...' && sleep 1; done;
        /usr/bin/mc mb --quiet --ignore-existing myminio/$MINIO_BUCKET_NAME;
        /usr/bin/mc anonymous set download myminio/$MINIO_BUCKET_NAME;"
