# Generated by Django 4.1.1 on 2022-09-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cooking_time', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ingredients', models.TextField(default='ingredients displayed of this recipe when it is available')),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('instructions', models.TextField(default='instructions displayed of this recipe when it is available')),
            ],
        ),
    ]
