# Generated by Django 4.1.1 on 2022-10-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="photo",
            field=models.FileField(default="photos/missing.png", upload_to="photos"),
        ),
    ]
