# Generated by Django 4.1.1 on 2022-10-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="notes",
        ),
    ]
